/***********************************************************************/
/*                                                                     */
/*  FILE        :3J_LCD.c                                              */
/*  DATE        :Fri, Nov 20, 2020                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3062F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

//3年次情報科
//C言語による機械制御

#define	PBDDR	(*(volatile unsigned char *)0xFEE00A)
#define	P4DDR	(*(volatile unsigned char *)0xFEE003)
#define	PBDR	(*(volatile unsigned char *)0xFFFFDA)
#define	P4DR	(*(volatile unsigned char *)0xFFFFD3)

void LCD_OUT8(unsigned char R0L, unsigned char R0H);
void wait_ms(unsigned long tm);

void main (void)
{
	//16進数 ==> 7セグメンントLEDデータ
	const unsigned  char TBL[]={0x47, 0x2E, 0x4E, 0x2E, 0x43, 0x2E, 0x54, 0x2E, 0x20, 0xB8, 0xDE, 0xDD, 0xCF, 0xBA, 0xB3, 0xB7, 0xDE, 0xAE, 0xB3, 0xBA, 0xB3, 0xC4,	0xB3, 0xBE, 0xDD, 0xD3, 0xDD, 0xB6, 0xDE, 0xAF, 0xBA, 0xB3};
	unsigned  char	R0L, R0H, R2L, ER1;
	unsigned  int	i;
	
	//ポートの設定
	//スタックポインタの設定は？
	R0L		=	0xFF;
	P4DDR	=	0xFF;	//ポート4を出力に設定
	PBDDR	=	0xFF;	//ポートBを出力に設定
	R0H		=	0x00;	//制御信号の初期値
	
	//ソフトウェアリセット
	wait_ms(45);
	R0L		=	0x30;	//instruction,DL = 1
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	wait_ms(5);
	R0L		=	0x30;	//instruction,DL = 1
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	wait_ms(1);
	R0L		=	0x30;	//instruction,DL = 1
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	
	//ファンクションリセット
	R0L		=	0x38;	//instruction, DL = 1, N = 1, F = 0
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	wait_ms(2);
	R0L		=	0x0E;	//instruction, D = 1, C = 1, B = 0
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	wait_ms(2);
	R0L		=	0x01;	//instruction, クリア
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	wait_ms(2);
	R0L		=	0x06;	//instruction, I/D=1, S=0
	R0H		&=	0xFA;	//RS =  0, R/W = 0
	LCD_OUT8(R0L, R0H);
	
	//文字転送
	//1行目の転送

		R0L		=	0x00;
		R0H		=	0xFA;
		LCD_OUT8(R0L, R0H);
		wait_ms(1);
		R2L		=	0x10;
		R0L 	= 	TBL[i];
	for(i=0;i<16;i=i+1){
		R0H		|=	0x01;
		R0L		=	TBL[i];
		LCD_OUT8(R0L,R0H);
		R0H		&=	0xFA;
		}

	//2行目の転送
		R0L		=	0xC0;
		R0H		=	0xFA;
		LCD_OUT8(R0L, R0H);
		wait_ms(1);
		R2L		=	0x10;
		R0L		= 	TBL[16+i];
	for(i=0;i<16;i=i+1){
		R0H		|=	0x01;
		R0L		=	TBL[i+16];
		LCD_OUT8(R0L,R0H);
		R0H		&=	0xFA;
		}
		
		while(1);
}

void LCD_OUT8(unsigned char R0L,unsigned char R0H) {
	P4DR = R0H;
	R0H |= 0x02;
	P4DR = R0H;
	PBDR = R0L;
	wait_ms(1);
	R0H &= 0xFD;
	P4DR = R0H;
	wait_ms(1);
}




//1ミリ秒待機関数(クロック周波数25MHz想定)
void wait_ms(unsigned long tm) {
	unsigned short t;
	while(tm--){
		for(t = 0; t < 4165; t++);
	}
}
